### ISSUE TITLE
版权问题

### ISSUE THREAD

**Issue by hyouhaku** [ricefishtech/industry4.0-mes#1]
请保留原作者版权信息 这是对同行的基本尊重

**Comment by longting** [comment]
赞同，这个是拿别人的代码直接改项目名字
原地址 
https://github.com/qcadoo/mes

**Comment by ricefish888** [comment]
请注意，这里是讨论问题的地方！不要随意乱说。

**Comment by hyouhaku** [comment]
那么这个版权问题解决了吗? 还是没有看到原作者和保留AGPL许可证

**Comment by ricefish888** [comment]
所有的代码是开源的并且是没有修改包名的，另外有我们自己修改后的代码，你好好看清楚代码再说话。
另外，你已经使用过这个系统，为什么不开源出来？
